// ── BMN-Specific Types ────────────────────────────────────────
// Types for Brand Me Now creator/agency pipeline operations.
// Separated from enrichment types to enforce clean boundaries.

/** BMN Agency Partner Funnel stages */
export interface BmnAgencyStageMap {
  positive_reply: string;
  engaged: string;
  discovery_scheduled: string;
  discovery_completed: string;
  proposal_sent: string;
  negotiation: string;
  agreement_signed: string;
  onboarding: string;
  lost: string;
}

/** BMN Creator Investment Funnel stages */
export interface BmnCreatorStageMap {
  positive_reply: string;
  appt_booked: string;
  application_received: string;
  brand_builder_started: string;
  brand_builder_finished: string;
  manual_review: string;
  approved: string;
  rejected: string;
}

/** Cadence email generated by Claude for follow-up sequence */
export interface CadenceEmail {
  step: number;
  subject: string;
  body: string;
  delayHours: number;
}

/** Candidate discovered from GHL pipeline for follow-up cadence */
export interface FollowupCandidate {
  ghlContactId: string;
  ghlOpportunityId: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  instantlyConversation: string[];
}

/** Result of handling an inbound reply to a cadence email */
export interface CadenceReplyResult {
  action: 'replied' | 'escalated' | 'booked' | 'ignored';
  response?: string;
}

/** Cadence stats aggregation */
export interface CadenceStats {
  active: number;
  completed: number;
  replied: number;
  escalated: number;
  booked: number;
  totalSent: number;
}
