-- Migration 022: Brand Launchpad
-- Client-facing onboarding portal for BMN brand clients. Magic-link gated.
-- Flow: invited → intake_started → intake_complete → strategy_generated
--       → assets_uploading → submitted → in_review → approved → launched
-- Approval is the hard gate before any downstream BMN system (GHL workflows,
-- Meta Ads, store launch) can fire for the brand.

CREATE TABLE IF NOT EXISTS launchpad_brands (
  id TEXT PRIMARY KEY,                    -- 'lpb_<random>'
  slug TEXT UNIQUE NOT NULL,              -- url-safe brand slug, e.g. 'quinns-wellness'
  brand_name TEXT NOT NULL,
  founder_name TEXT,
  founder_email TEXT NOT NULL,
  founder_phone TEXT,

  status TEXT NOT NULL DEFAULT 'invited',
  -- invited | intake_started | intake_complete | strategy_generated
  -- | assets_uploading | submitted | in_review | needs_changes
  -- | approved | rejected | launched

  intake_data TEXT,                       -- JSON of BrandIntake (collected by wizard)
  strategy_package TEXT,                  -- JSON of StrategyPackage (generated by /socialmediamonster)
  strategy_generated_at TEXT,
  strategy_generation_error TEXT,

  drive_folder_id TEXT,                   -- Google Drive folder ID for this brand (under BMN/Clients/)
  drive_folder_url TEXT,                  -- shareable URL

  launch_date TEXT,                       -- ISO date — when 30-day sprint starts
  submitted_at TEXT,
  approved_at TEXT,
  approved_by TEXT,
  rejected_at TEXT,
  rejection_reason TEXT,
  launched_at TEXT,

  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_launchpad_brands_status ON launchpad_brands(status, created_at);
CREATE INDEX IF NOT EXISTS idx_launchpad_brands_email ON launchpad_brands(founder_email);

-- Magic links — opaque tokens that grant the client access to their wizard.
-- Tokens are long-lived (7 days default) and can be redeemed multiple times
-- until expires_at. We don't expire on first use because clients need to
-- come back to the portal across multiple sessions.
CREATE TABLE IF NOT EXISTS launchpad_magic_links (
  id TEXT PRIMARY KEY,                    -- 'mlt_<random>'
  brand_id TEXT NOT NULL,
  token TEXT UNIQUE NOT NULL,             -- 64-char hex, used in URL
  expires_at TEXT NOT NULL,
  first_used_at TEXT,                     -- timestamp first redeemed
  last_used_at TEXT,                      -- timestamp last accessed
  use_count INTEGER NOT NULL DEFAULT 0,
  revoked_at TEXT,                        -- admin can revoke a link
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (brand_id) REFERENCES launchpad_brands(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_launchpad_magic_token ON launchpad_magic_links(token);
CREATE INDEX IF NOT EXISTS idx_launchpad_magic_brand ON launchpad_magic_links(brand_id);

-- Asset uploads — files the client uploads (logo, photos, finalized posts, video).
-- Files live on Google Drive; we store the Drive ID + public URL.
CREATE TABLE IF NOT EXISTS launchpad_assets (
  id TEXT PRIMARY KEY,                    -- 'lpa_<random>'
  brand_id TEXT NOT NULL,

  asset_type TEXT NOT NULL,
  -- 'logo' | 'product_photo' | 'founder_photo' | 'brand_guide'
  -- | 'finalized_post' | 'video' | 'audio' | 'other'

  filename TEXT NOT NULL,
  drive_file_id TEXT,                     -- Google Drive file ID
  drive_file_url TEXT,                    -- shareable URL (webViewLink)
  mime_type TEXT,
  size_bytes INTEGER,

  metadata TEXT,                          -- JSON: { day_number?, pillar_number?, caption?, notes? }

  uploaded_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (brand_id) REFERENCES launchpad_brands(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_launchpad_assets_brand ON launchpad_assets(brand_id, asset_type);

-- Per-module review state — admin can approve / request changes / leave feedback
-- on each of the 7 strategy modules independently.
CREATE TABLE IF NOT EXISTS launchpad_module_reviews (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  brand_id TEXT NOT NULL,
  module_number INTEGER NOT NULL,         -- 1-7
  status TEXT NOT NULL DEFAULT 'pending', -- pending | approved | needs_changes
  feedback TEXT,                          -- admin feedback to the client (markdown)
  reviewed_by TEXT,
  reviewed_at TEXT,
  client_revised_at TEXT,                 -- when client submitted a revised version
  UNIQUE (brand_id, module_number),
  FOREIGN KEY (brand_id) REFERENCES launchpad_brands(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_launchpad_reviews_brand ON launchpad_module_reviews(brand_id);

-- Status audit trail — full transition history per brand.
CREATE TABLE IF NOT EXISTS launchpad_status_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  brand_id TEXT NOT NULL,
  from_status TEXT,
  to_status TEXT NOT NULL,
  actor TEXT NOT NULL,                    -- 'client' | 'admin' | 'system'
  actor_email TEXT,
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (brand_id) REFERENCES launchpad_brands(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_launchpad_status_log_brand ON launchpad_status_log(brand_id, created_at);
