import {
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  TableRow,
  TableCell,
  Table,
  WidthType,
  ShadingType,
} from 'docx';
import { heading, bodyText, bulletPoint, numberedStep } from './docx-helpers';
import { sectionGap, boldBodyText } from './system-overview-sections';

// ── Sections 5-17: Detailed feature documentation ──────────
export function buildDetailedSections(): (Paragraph | Table)[] {
  return [
    // 5. Lead Enrichment & Scoring
    heading('5. Lead Enrichment & Scoring Pipeline', HeadingLevel.HEADING_1),
    bodyText('Every lead that enters the system goes through an automated enrichment pipeline:'),
    sectionGap(),
    numberedStep(1, 'Data Intake', 'Leads enter via CSV upload, LinkedIn scrape, Instagram scrape, webhook, Meta Ads, or manual entry.'),
    numberedStep(2, 'Email Validation', 'Email format is validated. Leads without valid emails are rejected with clear error messages.'),
    numberedStep(3, 'Deduplication', 'The system checks for existing leads with the same email + company combination. Duplicates are skipped.'),
    numberedStep(4, 'People Data Labs Enrichment', 'PDL returns: full name, job title, company name, company size, industry, location, LinkedIn URL, skills, education, and more. Results are cached for 30 days.'),
    numberedStep(5, 'Hunter.io Email Verification', 'Verifies email deliverability. Returns a confidence score and flags risky addresses. Results cached for 7 days.'),
    numberedStep(6, 'AI Scoring', 'Claude AI evaluates the enriched profile against your custom Ideal Customer Profile (ICP). Returns a score 0-100 with detailed reasoning.'),
    numberedStep(7, 'Label Assignment', 'Score translates to a label: Hot (80-100), Warm (60-79), Cool (40-59), Cold (0-39), or Disqualified.'),
    numberedStep(8, 'Auto-Tagging', 'AI applies relevant tags: accredited investor, C-suite, decision maker, etc.'),
    numberedStep(9, 'Cold Email Eligibility', 'System checks exclusion rules (domain, source, tag) and known contacts list before approving for outreach.'),
    numberedStep(10, 'CRM Push', 'Qualifying leads are automatically pushed to GoHighLevel with enrichment data as custom fields and auto-applied tags.'),
    numberedStep(11, 'Campaign Queue', 'Approved leads are imported into the target Instantly campaign for cold email sequencing.'),
    numberedStep(12, 'Event Logging', 'Every step is logged to the audit trail with timestamps for full traceability.'),
    sectionGap(),
    boldBodyText('Custom Scoring Prompt', 'Each company has its own ICP scoring prompt. The AI evaluates leads against criteria like industry, company size, job title seniority, geography, and revenue potential.'),
    boldBodyText('Score Thresholds', 'Configurable per company \u2014 set the minimum score for auto-approval, auto-GHL push, and cold email eligibility.'),
    sectionGap(),

    // 6. Cold Email Campaign Engine
    heading('6. Cold Email Campaign Engine', HeadingLevel.HEADING_1),
    bodyText('Powered by Instantly integration with full bi-directional sync:'),
    sectionGap(),
    heading('Campaign Management', HeadingLevel.HEADING_3),
    bulletPoint('Create, pause, resume, and monitor email campaigns'),
    bulletPoint('View per-step analytics: sent, opened, replied, bounced for each email in the sequence'),
    bulletPoint('Track open rates, reply rates, bounce rates, and click rates across all campaigns'),
    bulletPoint('Manage email sending accounts with warmup status and deliverability scores'),
    bulletPoint('Support for multiple workspaces and campaign subsequences'),
    sectionGap(),
    heading('AI Campaign Writer', HeadingLevel.HEADING_3),
    bulletPoint('Select any existing campaign and let Claude AI analyze its performance'),
    bulletPoint('AI generates 3 new email variations with different subject lines and body copy'),
    bulletPoint('Each variation includes reasoning for why it should perform better'),
    bulletPoint('One-click copy to clipboard for immediate use'),
    sectionGap(),
    heading('Lead Management', HeadingLevel.HEADING_3),
    bulletPoint('Bulk import leads to campaigns from the enrichment pipeline'),
    bulletPoint('Track lead engagement: sent, opened, replied, bounced per lead'),
    bulletPoint('Unibox integration for centralized inbox management across all campaigns'),
    sectionGap(),

    // 7. AI Reply Management
    heading('7. AI-Powered Reply Management', HeadingLevel.HEADING_1),
    bodyText('When prospects reply to cold emails, the system handles the conversation intelligently:'),
    sectionGap(),
    numberedStep(1, 'Reply Detection', 'Incoming emails are captured via Instantly webhook integration in real-time.'),
    numberedStep(2, 'Thread Creation', 'Each unique email conversation is organized into a thread with full message history.'),
    numberedStep(3, 'Sentiment Analysis', 'Claude AI analyzes the reply for sentiment: interested, not interested, meeting request, question, objection, unsubscribe request.'),
    numberedStep(4, 'Playbook Retrieval', 'The system loads the company-specific playbook containing: company description, value propositions, ICP definition, communication tone, objection handlers, conversation goals, escalation triggers, and meeting booking URL.'),
    numberedStep(5, 'Context Assembly', 'AI receives the full context: prospect enrichment data, lead score, all previous messages, playbook rules, and conversation goals.'),
    numberedStep(6, 'Reply Generation', 'Claude Sonnet generates an intelligent, personalized reply that addresses the prospect\'s specific points while advancing the conversation toward the goal (meeting booking, qualification, etc.).'),
    numberedStep(7, 'Auto-Send or Escalate', 'If auto-reply count is below the configured maximum, the reply is sent automatically. If an escalation trigger is detected (e.g., pricing request, legal question), the thread is flagged for human review.'),
    numberedStep(8, 'Conversion Tracking', 'When a prospect books a meeting or requests information, the thread is marked as "converted" with the conversion type.'),
    sectionGap(),
    boldBodyText('Playbook System', 'Each company maintains a detailed playbook that trains the AI on how to communicate. This includes tone of voice, value propositions, common objections with suggested responses, escalation triggers, and booking links.'),
    sectionGap(),

    // 8. CRM Integration
    heading('8. CRM Integration \u2014 GoHighLevel', HeadingLevel.HEADING_1),
    bodyText('Deep integration with GoHighLevel for full CRM automation:'),
    sectionGap(),
    bulletPoint('Contact Management \u2014 Create, update, search contacts. Sync enrichment data as custom fields.'),
    bulletPoint('Tag System \u2014 Auto-apply tags based on lead score, source, and enrichment data. Manage tags in bulk.'),
    bulletPoint('Pipeline Management \u2014 Visualize deal stages, track opportunity values, move contacts through pipeline.'),
    bulletPoint('Workflow Automation \u2014 Trigger GHL workflows for qualified leads (nurture sequences, task creation, notifications).'),
    bulletPoint('Two-Way Sync \u2014 Background sync every 5 minutes keeps contacts, tags, and pipeline data current.'),
    bulletPoint('Multi-Location \u2014 Each company has its own GHL location with isolated contacts and workflows.'),
    sectionGap(),

    // 9. Social Media Suite
    heading('9. Social Media Outreach Suite', HeadingLevel.HEADING_1),
    heading('LinkedIn Module', HeadingLevel.HEADING_2),
    bulletPoint('Profile Scraper \u2014 Extract professional profiles: headline, company, location, skills, experience'),
    bulletPoint('People Search \u2014 Find profiles by keywords and location filters'),
    bulletPoint('Company Scraper \u2014 Extract company data: industry, employee count, headquarters, description'),
    bulletPoint('Job Search \u2014 Find job postings by title and location'),
    bulletPoint('Import as Leads \u2014 Convert scraped profiles directly into enrichment pipeline leads'),
    sectionGap(),
    heading('Instagram Module', HeadingLevel.HEADING_2),
    bulletPoint('Profile Scraper \u2014 Analyze any public profile: followers, posts, engagement rate, bio'),
    bulletPoint('Hashtag Research \u2014 Scrape and analyze hashtag performance: average likes, top posts, engagement trends'),
    bulletPoint('Competitor Compare \u2014 Side-by-side comparison of multiple profiles: followers, engagement, growth'),
    bulletPoint('Reel Scraper \u2014 Extract reel content and engagement metrics'),
    bulletPoint('Post Scraper \u2014 Analyze individual posts: likes, comments, caption, engagement'),
    sectionGap(),
    heading('Instagram DM Campaigns', HeadingLevel.HEADING_2),
    bulletPoint('Multi-Step Sequences \u2014 Create DM campaigns with timed message steps (e.g., Day 1, Day 3, Day 7)'),
    bulletPoint('Template Variables \u2014 Personalize messages with {{username}}, {{full_name}}, {{bio_snippet}}'),
    bulletPoint('Hashtag Lead Import \u2014 Automatically scrape users posting under target hashtags and add to campaign'),
    bulletPoint('Competitor Lead Import \u2014 Scrape followers/commenters of competitor accounts'),
    bulletPoint('Rate Limiting \u2014 Configurable daily limits and random delays to avoid detection'),
    bulletPoint('Real-Time Progress \u2014 WebSocket broadcasts show live send progress and reply tracking'),
    sectionGap(),
    heading('WhatsApp Cloud API', HeadingLevel.HEADING_2),
    bulletPoint('Text Messages \u2014 Send plain text to any phone number (E.164 format)'),
    bulletPoint('Template Messages \u2014 Send pre-approved WhatsApp templates with variables'),
    bulletPoint('Media Messages \u2014 Send images and documents with captions'),
    bulletPoint('Phone Management \u2014 View configured sender numbers with quality ratings'),
    bulletPoint('Template Library \u2014 Browse all approved, pending, and rejected message templates'),
    sectionGap(),

    // 10. Meta Ads
    heading('10. Advertising Management \u2014 Meta Ads', HeadingLevel.HEADING_1),
    bulletPoint('Account Overview \u2014 Ad account info, currency, timezone, spend limits'),
    bulletPoint('Campaign CRUD \u2014 Create, pause, activate, and monitor Facebook/Instagram ad campaigns'),
    bulletPoint('KPI Dashboard \u2014 Impressions, clicks, CTR, CPC, CPM, reach, frequency, spend'),
    bulletPoint('Daily Spend Trends \u2014 Time-series chart showing spend over selected date range'),
    bulletPoint('Demographic Breakdowns \u2014 Insights by age, gender, and geography'),
    bulletPoint('Audience Targeting \u2014 Estimate audience sizes for targeting specifications'),
    bulletPoint('Date Presets \u2014 Quick filters: Today, Yesterday, 7 Days, 30 Days, custom range'),
    sectionGap(),

    // 11. Web Scraping
    heading('11. Web Scraping & Data Collection', HeadingLevel.HEADING_1),
    bodyText('Powered by Apify with a unified scraping hub:'),
    sectionGap(),
    heading('Available Scrapers', HeadingLevel.HEADING_3),
    bulletPoint('Google Search \u2014 Scrape search results for any query'),
    bulletPoint('LinkedIn Profiles \u2014 Extract professional profile data from URLs'),
    bulletPoint('LinkedIn Companies \u2014 Extract company pages with employee data'),
    bulletPoint('Instagram Profiles \u2014 Scrape profile metrics and recent posts'),
    bulletPoint('Instagram Hashtags \u2014 Scrape posts under any hashtag with engagement data'),
    bulletPoint('Generic Website Scraper \u2014 Extract structured data from any URL'),
    sectionGap(),
    heading('Management Features', HeadingLevel.HEADING_3),
    bulletPoint('Run History \u2014 Track all scraping jobs: status, duration, actor ID, results'),
    bulletPoint('Saved Tasks \u2014 Pre-configure scrapers for one-click repeat execution'),
    bulletPoint('Datasets \u2014 Browse and export historical scraping results'),
    bulletPoint('Account Usage \u2014 Monitor compute units, data transfer, proxy credits, and monthly cost'),
    bulletPoint('Async Jobs \u2014 Long-running scrapes return immediately with a job ID for status polling'),
    sectionGap(),

    // 12. Competitors
    heading('12. Competitor Intelligence', HeadingLevel.HEADING_1),
    bulletPoint('Website Monitoring \u2014 Track competitor URLs for content changes'),
    bulletPoint('Change Detection \u2014 Automatic detection of title, description, and content hash changes'),
    bulletPoint('Change History \u2014 Timeline view of all detected changes with timestamps'),
    bulletPoint('Status Tracking \u2014 Green dot for live sites, red for errors, gray for unknown'),
    bulletPoint('Background Sync \u2014 Competitor websites are checked automatically every 5 minutes'),
    sectionGap(),

    // 13. Business Intelligence
    heading('13. Business Intelligence & AI Insights', HeadingLevel.HEADING_1),
    heading('Dashboard Analytics', HeadingLevel.HEADING_2),
    bulletPoint('Campaign Performance Chart \u2014 Bar chart comparing open rates vs reply rates'),
    bulletPoint('Task Distribution \u2014 Pie chart showing TODO / In Progress / Done breakdown'),
    bulletPoint('Agent Health \u2014 Radar chart displaying success rates across all automation agents'),
    bulletPoint('Alert Severity \u2014 Bar chart breaking down critical / warning / info alerts'),
    sectionGap(),
    heading('AI Discovery Engine', HeadingLevel.HEADING_2),
    bulletPoint('Auto-generated insights from all connected platforms (campaigns, agents, enrichment, ads)'),
    bulletPoint('Categorized as: Performance alerts, Action Needed, Trends, Milestones'),
    bulletPoint('Save/bookmark important discoveries for reference'),
    bulletPoint('Auto-refreshes every 60 seconds for real-time intelligence'),
    sectionGap(),
    heading('AI Dashboard Assistant', HeadingLevel.HEADING_2),
    bulletPoint('Natural language Q&A about all dashboard data'),
    bulletPoint('Ask questions like: "How are my campaigns doing?", "Which agents need attention?"'),
    bulletPoint('AI queries live database data to answer questions with specific numbers'),
    bulletPoint('Conversation history preserved for follow-up questions'),
    sectionGap(),
    heading('Data Export', HeadingLevel.HEADING_2),
    bulletPoint('Executive Summary \u2014 Download a Word document with live KPIs, pipeline data, campaign stats'),
    bulletPoint('System Overview \u2014 This document, with full platform documentation'),
    bulletPoint('User Guide \u2014 Step-by-step feature guide as downloadable Word document'),
    bulletPoint('Lead Export \u2014 Export leads as CSV or JSON with filtering by status and score'),
    bulletPoint('Campaign Export \u2014 Export campaign data with performance statistics'),
    sectionGap(),

    // 14. Task Management
    heading('14. Task Management & Team Coordination', HeadingLevel.HEADING_1),
    bulletPoint('Dual View \u2014 Switch between Table view (sortable columns) and Kanban board (drag-and-drop)'),
    bulletPoint('Priority System \u2014 Urgent (red), High (orange), Medium (yellow), Low (gray)'),
    bulletPoint('Due Dates \u2014 Calendar date picker with visual countdown indicators'),
    bulletPoint('Assignees \u2014 Assign tasks to team members with company association'),
    bulletPoint('Quick Complete \u2014 One-click checkbox to mark tasks as done'),
    bulletPoint('Create Tasks \u2014 Inline creation with title, priority, due date, and assignee'),
    bulletPoint('AI Task Creation \u2014 Tell the AI Assistant "Create a task to follow up with John" and it creates it for you'),
    sectionGap(),

    // 15. BTR Conference
    heading('15. Conference & Networking Coordinator', HeadingLevel.HEADING_1),
    bodyText('Purpose-built for the BTR Conference (Nashville) with two-person sales coordination:'),
    sectionGap(),
    heading('Team Strategy', HeadingLevel.HEADING_3),
    bulletPoint('Colby \u2014 Inside strategy (panels + meetings)'),
    bulletPoint('Ryan \u2014 Outside strategy (closer + follow-ups)'),
    sectionGap(),
    heading('Contact Organization', HeadingLevel.HEADING_3),
    bulletPoint('Tier System \u2014 Tier 1 (highest priority, red), Tier 2 (medium, yellow), Tier 3 (lower, blue)'),
    bulletPoint('Segments \u2014 Builder, Investor, Lender, Operator'),
    bulletPoint('Assignee \u2014 Each contact assigned to Colby or Ryan'),
    sectionGap(),
    heading('Outreach Pipeline', HeadingLevel.HEADING_3),
    bodyText('10-stage progression tracking:'),
    bulletPoint('Pre-Outreach \u2192 LinkedIn Sent \u2192 LinkedIn Connected \u2192 Email Sent \u2192 Email Replied \u2192 Meeting Scheduled \u2192 Met at Conference \u2192 Proposal Sent \u2192 Follow-Up \u2192 Won'),
    sectionGap(),
    heading('Dashboard Stats', HeadingLevel.HEADING_3),
    bulletPoint('Total contacts, Tier 1/2 counts, already contacted, meetings scheduled, outreach completion %'),
    bulletPoint('Countdown timer to conference date (color-coded urgency)'),
    bulletPoint('List and Kanban views for contact management'),
    sectionGap(),

    // 16. Infrastructure
    heading('16. Infrastructure & Automation Agents', HeadingLevel.HEADING_1),
    heading('Automation Agents', HeadingLevel.HEADING_2),
    bulletPoint('Monitor all background automation workers with real-time status indicators'),
    bulletPoint('Agent types: CloudCode, GHL Workflow, OpenClaw, Scheduler, Webhook, Manual'),
    bulletPoint('Track success rates, run durations, costs per run, and error messages'),
    bulletPoint('View last 10 runs per agent with full execution details'),
    bulletPoint('Automatic alerts when agent health drops below threshold'),
    sectionGap(),
    heading('OpenClaw ACP', HeadingLevel.HEADING_2),
    bulletPoint('Machine Management \u2014 Start, stop, restart connected machines'),
    bulletPoint('System Status \u2014 Online/offline indicator with latency monitoring and history sparkline'),
    bulletPoint('Terminal \u2014 Send commands directly to infrastructure with full response log'),
    bulletPoint('Diagnostics \u2014 Run system health checks on demand'),
    sectionGap(),
    heading('Background Sync Engine', HeadingLevel.HEADING_2),
    bodyText('6 parallel sync jobs run automatically every 5 minutes:'),
    bulletPoint('Instantly Sync \u2014 Campaign stats, lead counts, step analytics'),
    bulletPoint('GoHighLevel Sync \u2014 Contacts, tags, workflows, pipeline stages'),
    bulletPoint('OpenClaw Sync \u2014 Machine status and automation health'),
    bulletPoint('Meta Ads Sync \u2014 Campaign performance and spend data'),
    bulletPoint('Competitor Sync \u2014 Website snapshots and content change detection'),
    bulletPoint('Enrichment Sync \u2014 Process pending leads in batch'),
    bodyText('After sync completes, an AI Discovery job generates fresh insights from all platforms.'),
    sectionGap(),

    // 17. Bulk CSV Import
    heading('17. Bulk CSV Import System', HeadingLevel.HEADING_1),
    bodyText('Upload CSV files of cold leads with a 4-step wizard:'),
    sectionGap(),
    numberedStep(1, 'Upload & Select Company', 'Drag-and-drop CSV file, select target company. File is parsed in the browser \u2014 nothing is sent until confirmed.'),
    numberedStep(2, 'Column Mapping', 'Auto-detects common headers (Email, First Name, Last Name, Phone, Company, Job Title, LinkedIn URL). Manual override with dropdowns.'),
    numberedStep(3, 'Preview & Configure', 'Table preview of first 5 rows. Toggle auto-process (enrich + score + CRM push + cold email). Select target Instantly campaign.'),
    numberedStep(4, 'Upload & Monitor', 'Real-time progress bar via WebSocket. Counters for inserted, duplicates, errors, and enrichment progress. Cancel button for mid-batch abort.'),
    sectionGap(),
    boldBodyText('Deduplication', 'Leads are deduplicated by email + company. Same email for the same company is never double-imported.'),
    boldBodyText('Large Batches', 'Supports 1,000+ row CSVs. Processing happens in background batches of 5 with API rate limiting.'),
    boldBodyText('Import History', 'All imports tracked with status, row counts, and error details for auditing.'),
    sectionGap(),
  ];
}

// ── Sections 18-22 and closing ─────────────────────────────
export function buildClosingSections(companies: any[], genDate: string): (Paragraph | Table)[] {
  return [
    // 18. Data Export
    heading('18. Data Export & Reporting', HeadingLevel.HEADING_1),
    bodyText('Available downloadable documents:'),
    sectionGap(),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({ tableHeader: true, children: [
          new TableCell({ shading: { type: ShadingType.SOLID, color: '1a202c' }, children: [new Paragraph({ children: [new TextRun({ text: 'Document', bold: true, color: 'ffffff', size: 20 })] })] }),
          new TableCell({ shading: { type: ShadingType.SOLID, color: '1a202c' }, children: [new Paragraph({ children: [new TextRun({ text: 'Format', bold: true, color: 'ffffff', size: 20 })] })] }),
          new TableCell({ shading: { type: ShadingType.SOLID, color: '1a202c' }, children: [new Paragraph({ children: [new TextRun({ text: 'Contents', bold: true, color: 'ffffff', size: 20 })] })] }),
        ] }),
        ...([
          ['Executive Summary', '.docx', 'Live KPIs, lead pipeline, campaign stats, agent status, alerts, priority tasks'],
          ['System Overview', '.docx', 'Full platform documentation with all features, workflows, and integrations'],
          ['User Guide', '.docx', 'Step-by-step walkthroughs for every feature with AI commands'],
          ['Lead Export', '.csv / .json', 'Filtered lead data with enrichment fields, scores, and status'],
          ['Campaign Export', '.csv / .json', 'Campaign data with performance statistics'],
        ] as [string, string, string][]).map(([doc, format, contents]) =>
          new TableRow({ children: [
            new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: doc, size: 20 })] })] }),
            new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: format, size: 20 })] })] }),
            new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: contents, size: 20 })] })] }),
          ] }),
        ),
      ],
    }),
    sectionGap(),

    // 19. External Integrations
    heading('19. External API Integrations', HeadingLevel.HEADING_1),
    bodyText('The platform connects to 15+ external services:'),
    sectionGap(),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({ tableHeader: true, children: [
          new TableCell({ shading: { type: ShadingType.SOLID, color: '1a202c' }, width: { size: 2000, type: WidthType.DXA }, children: [new Paragraph({ children: [new TextRun({ text: 'Service', bold: true, color: 'ffffff', size: 18 })] })] }),
          new TableCell({ shading: { type: ShadingType.SOLID, color: '1a202c' }, children: [new Paragraph({ children: [new TextRun({ text: 'Purpose', bold: true, color: 'ffffff', size: 18 })] })] }),
        ] }),
        ...([
          ['Instantly', 'Cold email platform \u2014 campaigns, leads, sequences, reply webhooks, analytics, account management'],
          ['GoHighLevel', 'CRM \u2014 contacts, tags, workflows, pipelines, opportunities, SMS/email sending'],
          ['People Data Labs', 'B2B data enrichment \u2014 person profiles (job, company, location, skills, education, social)'],
          ['Hunter.io', 'Email verification \u2014 deliverability scoring, domain email discovery'],
          ['Claude AI (Anthropic)', 'AI engine \u2014 lead scoring, sentiment analysis, auto-reply generation, campaign writing, discovery insights'],
          ['Apify', 'Web scraping \u2014 LinkedIn, Instagram, Google, generic websites. Async job management'],
          ['Meta Graph API', 'Ad management \u2014 campaigns, insights, audiences, creatives, spend tracking'],
          ['WhatsApp Cloud API', 'Messaging \u2014 text, templates, images, documents. Phone and template management'],
          ['OpenClaw', 'Infrastructure \u2014 remote machine management, command execution, diagnostics'],
          ['Instagram (via Apify)', 'Social scraping \u2014 profiles, hashtags, posts, reels, engagement metrics'],
          ['LinkedIn (via Apify)', 'Professional scraping \u2014 profiles, companies, job listings, employee data'],
        ] as [string, string][]).map(([service, purpose]) =>
          new TableRow({ children: [
            new TableCell({ width: { size: 2000, type: WidthType.DXA }, children: [new Paragraph({ children: [new TextRun({ text: service, bold: true, size: 18 })] })] }),
            new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: purpose, size: 18 })] })] }),
          ] }),
        ),
      ],
    }),
    sectionGap(),

    // 20. WebSocket Architecture
    heading('20. Real-Time WebSocket Architecture', HeadingLevel.HEADING_1),
    bodyText('The platform uses WebSocket connections for real-time updates without page refreshes:'),
    sectionGap(),
    bulletPoint('sync_complete \u2014 Triggers automatic data refresh when background sync finishes'),
    bulletPoint('alert \u2014 New critical/warning alerts appear instantly in the alerts feed'),
    bulletPoint('enrichment_update \u2014 Lead enrichment status changes reflected in real-time'),
    bulletPoint('reply_received \u2014 New email replies appear immediately in the thread view'),
    bulletPoint('campaign_progress \u2014 Instagram DM campaign progress updates live'),
    bulletPoint('import_progress \u2014 Bulk CSV import processing tracked with live progress bar'),
    sectionGap(),
    boldBodyText('Auto-Reconnect', 'If the WebSocket connection drops, the client automatically reconnects after 3 seconds.'),
    sectionGap(),

    // 21. Key Workflows
    heading('21. Key Automated Workflows', HeadingLevel.HEADING_1),
    sectionGap(),
    heading('Workflow A: Full Lead Pipeline (End-to-End)', HeadingLevel.HEADING_2),
    bodyText('CSV Upload \u2192 Validate \u2192 Deduplicate \u2192 Enrich (PDL) \u2192 Verify Email (Hunter) \u2192 AI Score (Claude) \u2192 Tag \u2192 Check Rules \u2192 Push to GHL \u2192 Queue for Instantly \u2192 Cold Email Sequence \u2192 Reply Detection \u2192 AI Sentiment Analysis \u2192 Auto-Reply or Escalate \u2192 Conversion Tracking'),
    sectionGap(),
    heading('Workflow B: Cold Email Reply Handling', HeadingLevel.HEADING_2),
    bodyText('Incoming Reply Webhook \u2192 Create/Update Thread \u2192 Analyze Sentiment \u2192 Load Company Playbook \u2192 Assemble Context (prospect data + history) \u2192 Claude Generates Reply \u2192 Auto-Send or Escalate \u2192 Log Message \u2192 Update Thread Status'),
    sectionGap(),
    heading('Workflow C: Instagram DM Campaign', HeadingLevel.HEADING_2),
    bodyText('Create Campaign \u2192 Define Multi-Step Message Sequence \u2192 Import Leads (from hashtag scrape or competitor followers) \u2192 Start Campaign \u2192 Send Step 1 with Random Delays \u2192 Track Replies \u2192 Send Step 2 After Delay \u2192 Monitor Reply Rate \u2192 Generate Stats'),
    sectionGap(),
    heading('Workflow D: LinkedIn to Pipeline', HeadingLevel.HEADING_2),
    bodyText('LinkedIn Search \u2192 Scrape Profiles \u2192 Import as Leads \u2192 Enrich \u2192 Score \u2192 Push to GHL Pipeline \u2192 Queue for Cold Email'),
    sectionGap(),
    heading('Workflow E: Background Sync Cycle (Every 5 Min)', HeadingLevel.HEADING_2),
    bodyText('Instantly Sync + GHL Sync + OpenClaw Sync + Meta Ads Sync + Competitor Sync + Enrichment Sync \u2192 All run in parallel \u2192 AI Discovery engine generates insights \u2192 WebSocket broadcasts completion \u2192 UI auto-refreshes'),
    sectionGap(),

    // 22. Multi-Tenant
    heading('22. Multi-Tenant Company Architecture', HeadingLevel.HEADING_1),
    bodyText('The platform supports multiple companies with full data isolation:'),
    sectionGap(),
    heading('Current Companies', HeadingLevel.HEADING_3),
    ...companies.map((c: any) =>
      bulletPoint(`${c.name} (ID: ${c.id})`),
    ),
    sectionGap(),
    heading('Per-Company Isolation', HeadingLevel.HEADING_3),
    bulletPoint('Separate GoHighLevel location with unique API credentials'),
    bulletPoint('Separate Instantly account and email sending infrastructure'),
    bulletPoint('Custom enrichment configuration (scoring prompt, ICP criteria, thresholds)'),
    bulletPoint('Company-specific playbook for AI reply generation (tone, value props, objection handlers)'),
    bulletPoint('Independent cold email exclusion rules and known contacts'),
    bulletPoint('Filtered views \u2014 select a company from the sidebar to see only that company\'s data'),
    bulletPoint('"All Companies" mode for cross-company executive view'),
    sectionGap(),
    sectionGap(),

    // Closing
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 400, after: 200 },
      children: [new TextRun({ text: '\u2014 End of Document \u2014', size: 24, color: '999999', italics: true })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: `Master Dashboard Command Center | ${genDate}`, size: 20, color: 'aaaaaa' })],
    }),
  ];
}
